### ISSUE TITLE
Cool project!

### ISSUE THREAD

**Issue by tetreum** [przemyslawzaworski/Unity-GPU-Based-Occlusion-Culling#1]
I hope you make it work for HDRP, it would be useful for https://github.com/tetreum/brickcraft :p

**Comment by przemyslawzaworski** [comment]
In current state, HDRP don't support RWStructuredBuffer.

https://forum.unity.com/threads/rwstructuredbuffer-access-in-a-hdrp-shader.658639/

Eventually, there exists a less elegant workaround - using RenderTexture as read/write buffer and Texture2D.ReadPixels to get texture data from GPU to CPU.
