### ISSUE TITLE
Has this been tested on mobile/VR stadalone?

### ISSUE THREAD

**Issue by richdrummer33** [przemyslawzaworski/Unity-GPU-Based-Occlusion-Culling#11]
Next chance I get I want to test this out, but I just wanted to pop a question in here in case anyone has had experience doing this. 

Ps. I'm stoked to come across this. I was literally thinking of making a compute shader to do just this - now I don't have to do. As interesting as it may be, it saves a lot of time to not have to make it myself 😄.

If this really does yield Major performance benefits (and I suspect it would over other CPU based techniques), I'm surprised that Unity hasn't implemented this as a core feature.

**Comment by przemyslawzaworski** [comment]
It doesn't work in VR standalone build (Vulkan API - Meta Quest 3).
But works with Vulkan API under Windows, so probably it is caused with some hardware specific limitations, maybe Quest doesn't support earlydepthstencil or RWStructuredBuffer inside Pixel Shader.

**Comment by richdrummer33** [comment]
Yeah maybe incompatibility with Quest Vulkan extensions, who knows. Ty!

**Comment by richdrummer33** [comment]
Yeah maybe incompatibility with Quest Vulkan extensions, who knows. Ty!
