### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by JijaProGamer** [przemyslawzaworski/Unity-GPU-Based-Occlusion-Culling#5]
How would I install and set this up? Looking at the code it seems that you have to chose which meshes this applies to?

**Comment by przemyslawzaworski** [comment]
Yes. Add components HardwareOcclusion and HardwareOcclusionManager to empty gameobject. Then add gameobjects with renderers to HardwareOcclusion.Targets.

In the future I will update repository with new features. I developed extended version of this system for Tank Mechanic Simulator game: https://www.youtube.com/watch?v=vyWu8_EM0wY

**Comment by JijaProGamer** [comment]
Thank you, I quite appreciate your support!

**Comment by JijaProGamer** [comment]
HardwareOcclusion.Targets is a array, do I have to redo the array whenever I want to add  new object?
